const products = [
    {
        id: 1,
        image: 'product1.jpg',
        title: 'Product 1',
        description: 'This is the description for Product 1.',
        price: 19.99,
    },
    {
        id: 2,
        image: 'product2.jpg',
        title: 'Product 2',
        description: 'Product 2 is a great choice for your needs.',
        price: 29.99,
    },
    {
        id: 3,
        image: 'product3.jpg',
        title: 'Product 3',
        description: 'Description for Product 3 goes here.',
        price: 39.99,
    },
    {
        id: 4,
        image: 'product4.jpg',
        title: 'Product 4',
        description: 'Description for Product 4.',
        price: 49.99,
    },
    {
        id: 5,
        image: 'product5.jpg',
        title: 'Product 5',
        description: 'Product 5 is a fantastic option.',
        price: 59.99,
    },
    {
        id: 6,
        image: 'product6.jpg',
        title: 'Product 6',
        description: 'Product 6 description.',
        price: 69.99,
    },
    {
        id: 7,
        image: 'product7.jpg',
        title: 'Product 7',
        description: 'Product 7 description.',
        price: 79.99,
    },
    {
        id: 8,
        image: 'product8.jpg',
        title: 'Product 8',
        description: 'Description for Product 8.',
        price: 89.99,
    },
    {
        id: 9,
        image: 'product9.jpg',
        title: 'Product 9',
        description: 'Product 9 description.',
        price: 99.99,
    },
    {
        id: 10,
        image: 'product10.jpg',
        title: 'Product 10',
        description: 'Description for Product 10.',
        price: 109.99,
    },
    {
        id: 11,
        image: 'product11.jpg',
        title: 'Product 11',
        description: 'Product 11 description.',
        price: 119.99,
    },
    {
        id: 12,
        image: 'product12.jpg',
        title: 'Product 12',
        description: 'Product 12 description.',
        price: 129.99,
    },
    {
        id: 13,
        image: 'product13.jpg',
        title: 'Product 13',
        description: 'Description for Product 13.',
        price: 139.99,
    },
    {
        id: 14,
        image: 'product14.jpg',
        title: 'Product 14',
        description: 'Product 14 is a great choice.',
        price: 149.99,
    },
    {
        id: 15,
        image: 'product15.jpg',
        title: 'Product 15',
        description: 'Product 15 description.',
        price: 159.99,
    },
    {
        id: 16,
        image: 'product16.jpg',
        title: 'Product 16',
        description: 'Description for Product 16.',
        price: 169.99,
    },
    {
        id: 17,
        image: 'product17.jpg',
        title: 'Product 17',
        description: 'Product 17 is an excellent option.',
        price: 179.99,
    },
    {
        id: 18,
        image: 'product18.jpg',
        title: 'Product 18',
        description: 'Product 18 description.',
        price: 189.99,
    },
    {
        id: 19,
        image: 'product19.jpg',
        title: 'Product 19',
        description: 'Description for Product 19.',
        price: 199.99,
    },
    {
        id: 20,
        image: 'product20.jpg',
        title: 'Product 20',
        description: 'Product 20 description.',
        price: 209.99,
    },
    {
        id: 21,
        image: 'product21.jpg',
        title: 'Product 21',
        description: 'Product 21 description.',
        price: 209.99,
    },
    {
        id: 22,
        image: 'product22.jpg',
        title: 'Product 22',
        description: 'Product 22 description.',
        price: 209.99,
    },
    {
        id: 23,
        image: 'product23.jpg',
        title: 'Product 23',
        description: 'Product 23 description.',
        price: 209.99,
    },
    {
        id: 24,
        image: 'product24.jpg',
        title: 'Product 24',
        description: 'Product 24 description.',
        price: 209.99,
    },
    {
        id: 25,
        image: 'product25.jpg',
        title: 'Product 25',
        description: 'Product 25 description.',
        price: 209.99,
    },
];

export default products;
